"use client"
import Head from "next/head";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import deved from "../public/dev-ed-wave.png";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import Image from "next/image";
import web1 from "public/web1.png";
import web2 from "public/web2.png";
import web3 from "public/web3.png";
import web4 from "public/web4.png";
import web5 from "public/web5.png";
import web6 from "public/web6.png";

export default function Home() {
  
  const [darkMode, setDarkMode] = useState(false);
 return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Maha Arif profile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
         <nav className="py-12 container flex justify-around flex-wrap dark:text-white">
           <h1 className="text-4xl flex gap-8 text-gray-600 dark:text-gray-400">
             <a href="https://twitter.com/MahaArif4854"> <AiFillTwitterCircle/></a>
             <a href="https://www.linkedin.com/in/maha-arif-6697a2107/"><AiFillLinkedin/></a>
             <a href="https://www.youtube.com/channel/UC-O9MjnW4LLS4-PtL3Wr-RA"> <AiFillYoutube  /></a>
              </h1>
              <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500  to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8 "
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="py-12 profile flex justify-center even:text-left even:flex-row">      
            <div className="bg-gradient-to-b from-teal-500 rounded-full w-36 h-36 relative overflow-hidden md:h-40 md:w-40">
              <Image src={deved} alt="" width={150} height={150}  />
            </div>
            <div>
            <h2 className="text-5xl text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Maha Arif
            </h2>
            <h3 className="text-4xl py-2 dark:text-white md:text-3xl">
              Developer and designer.
            </h3>
            
            <p className="text-1xl py-2 dark:text-gray-200 ">
              providing services for programming and 
            </p>
            <p className="text-1xl dark:text-gray-200">
            design, Join me and lets get cracking
            </p>
          </div>
          </div>
          <div>
            <h3 className="text-3xl  dark:text-white "><b><u>Services I offer</u></b></h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my journey as a freelance designer and
              developer, I have done remote work for
              <span className="text-teal-500"> agencies </span>
              consulted for <span className="text-teal-500">startups </span>
              and collaborated with talanted people to create digital products
              for both business and consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of services, including brand design,
              programming and teaching.
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image src={design} alt="" width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                Beautiful Designs
              </h3>
              <p className="py-2">
                Creating elegant designs suited for your needs following core
                design theory.
              </p>
              <h4 className="py-4 text-teal-600"><b>Design Tools I Use</b></h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
              <p className="text-gray-800 py-1">After Effect</p>
              <p className="text-gray-800 py-1">premiere</p>
              <p className="text-gray-800 py-1">Indesign</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={code} alt="" width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                Code your dream project
              </h3>
              <p className="py-2">
                Do you have an idea for your next great website? Lets make it a
                reality.
              </p>
              <h4 className="py-4 text-teal-600"><b>Developing Tools I Use</b></h4>
              <p className="text-gray-800 py-1">Nextjs</p>
              <p className="text-gray-800 py-1">WIX</p>
              <p className="text-gray-800 py-1">Wordpress</p>
              <p className="text-gray-800 py-1">Shopify</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={consulting} alt="" width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">Consulting</h3>
              <p className="py-2">
                Are you interested in feedback for your current project? I can
                give you tips and tricks to level it up.
              </p>
              <h4 className="py-4 text-teal-600"><b>Consulting</b></h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Nextjs</p>
              <p className="text-gray-800 py-1">Wordpress</p>
              <p className="text-gray-800 py-1">Figma</p>
              <p className="text-gray-800 py-1">Indesign</p>
            </div>
          </div>
        </section>
        
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white "><b><u>Portofolio</u></b></h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my journey as a freelance designer and
              developer, I have done remote work for agencies 
              consulted for startups 
              and collaborated with talanted people to create digital products
              for both business and consumer use. 
              I offer from a wide range of services, including brand design,
              programming and teaching.
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 ">
              <Image src={web1} width={100} height={100}
                className="rounded-lg object-cover" alt=""/>
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover" alt=""
                width={100}
                height={100}
               src={web2}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover" alt=""
                width={100}
                height={100}
                
                src={web3}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover" alt=""
                width={100}
                height={100}
                 src={web4}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover" alt=""
                width={100}
                height={100}
                src={web5}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover" alt=""
                width={100}
                height={100}
                src={web6}
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
} 